### ISSUE TITLE
Please add note to the Readme.md

### ISSUE THREAD

**Issue by Thisisnotgoingpublished** [hootan09/rfidCrack#1]
This part:

**When using the USB TTL cable issue the following command:

sudo cp contrib/libnfc/pn532_via_uart2usb.conf.sample /etc/nfc/devices.d/pn532_via_uart2usb.conf
If you connect the breakout board directly to your Raspberry PI’s UART pins you need to copy the following file:

sudo cp contrib/libnfc/pn532_uart_on_rpi.conf.sample /etc/nfc/devices.d/pn532_uart_on_rpi.conf**

Please write something like <i>`For example if you are using a pn532 device.`</i>

If you do not do so. It will lead people searching on the internet vainly. Only to find this, and it won't work. Cuz you force that nfc-list to use pn532 in the first place. https://github.com/nfc-tools/libnfc/issues/576

Someone did said that he reinstall the driver, restart his computer for 100 times and he pray to the nfc god everyday. LMAO

**Comment by hootan09** [comment]
Thanks. at the end of Readme I already mention this.

**Comment by Thisisnotgoingpublished** [comment]
It's not enough. I am for one still didn't see it.2022年9月23日 14:03，Mohammad Niki ***@***.***>写道：
Closed #1 as completed.

**Comment by hootan09** [comment]
ok. plz send a pull request for edit README
if you want to edit this repo.
